// Cartera de mora sembrada del demo de Banco Promerica.
//
// Las personas, las cuentas y los montos son INVENTADOS. Lo que sí es real es
// la forma: productos de banca salvadoreña, dólares, DUI enmascarado, números
// de ocho dígitos y tramos de mora como los mira un banco (1-30, 31-60, 61-90,
// más de 90).
//
// Dos fichas traen transcripción de llamada a propósito: son las que dejan
// probar el botón "Analizar con IA" sin marcar un solo teléfono.

import type { Deudor } from "./cobros-tipos";

// Ancla fija para que el demo se vea igual cada vez que se abre.
const HOY = "2026-08-17";

function dias(n: number): string {
  const t = Date.parse(`${HOY}T12:00:00Z`) - n * 86_400_000;
  return new Date(t).toISOString();
}

function fecha(n: number): string {
  return dias(n).slice(0, 10);
}

export const DEUDORES_SEMILLA: Deudor[] = [
  {
    id: "d1",
    nombre: "Luis Alberto Menjívar",
    documento: "0134****-7",
    telefono: "+50378541209",
    producto: "tarjeta",
    cuenta: "****4471",
    saldoTotal: 1840.5,
    montoVencido: 312.5,
    cuotaMensual: 156.25,
    diasMora: 34,
    ultimoPago: { fecha: fecha(48), monto: 156.25 },
    estado: "promesa_pago",
    riesgo: "bajo",
    sentimiento: "cooperativo",
    promesa: { monto: 312.5, fecha: fecha(-4), registrada: dias(2), origen: "ia" },
    proximaAccion: { tipo: "esperar_pago", cuando: fecha(-4) },
    resumenIa:
      "Se comprometió a pagar los 312.50 el viernes, cuando le depositan la quincena. Pidió que no lo llamen antes de esa fecha.",
    etiquetas: ["Quincena 15"],
    llamable: true,
    actualizado: dias(2),
    gestiones: [
      {
        id: "g1",
        tipo: "llamada",
        cuando: dias(2),
        autor: "ia",
        resultado: "promesa_pago",
        duracionSeg: 148,
        resumen:
          "Se comprometió a pagar los 312.50 el viernes, cuando le depositan la quincena. Pidió que no lo llamen antes de esa fecha.",
        transcript:
          "Agente: Buenos días, le saluda Camila, del área de servicio al cliente de Banco Promerica. ¿Hablo con Luis Alberto Menjívar?\nCliente: Sí, con él habla.\nAgente: Por seguridad, ¿me confirma los últimos cuatro dígitos de su documento?\nCliente: Sí, cuatro dos siete siete.\nAgente: Gracias, don Luis. Le llamo por su tarjeta de crédito, que tiene trescientos doce dólares con cincuenta pendientes, con treinta y cuatro días de atraso. ¿Me ayuda a resolverlo hoy?\nCliente: Fíjese que sí, lo que pasa es que a mí me pagan hasta el viernes. Ahorita no ando nada.\nAgente: Entiendo. ¿El viernes le quedaría bien para hacer el pago completo?\nCliente: Sí, el viernes sin falta le pago los trescientos doce.\nAgente: Perfecto. Entonces quedamos en trescientos doce dólares con cincuenta el viernes. ¿Correcto?\nCliente: Correcto. Y por favor no me estén llamando antes, que ando en el trabajo.\nAgente: Entendido, don Luis. Gracias por su tiempo, que esté bien.",
      },
    ],
  },
  {
    id: "d2",
    nombre: "Rosa Elena Portillo de Cruz",
    documento: "0298****-1",
    telefono: "+50370119088",
    correo: "relena.portillo@gmail.com",
    producto: "prestamo_personal",
    cuenta: "****9032",
    saldoTotal: 6420.0,
    montoVencido: 845.0,
    cuotaMensual: 422.5,
    diasMora: 62,
    ultimoPago: { fecha: fecha(75), monto: 422.5 },
    estado: "negociacion",
    riesgo: "medio",
    sentimiento: "cooperativo",
    proximaAccion: {
      tipo: "enviar_convenio",
      cuando: fecha(-1),
      nota: "Puede abonar 200 al mes, no la cuota completa.",
    },
    resumenIa:
      "Perdió el trabajo hace dos meses. Puede abonar 200 dólares mensuales, no los 422.50. Pidió que le manden opciones de refinanciamiento.",
    etiquetas: ["Sin empleo", "Pide convenio"],
    llamable: true,
    actualizado: dias(3),
    gestiones: [
      {
        id: "g2",
        tipo: "llamada",
        cuando: dias(3),
        autor: "ia",
        resultado: "quiere_negociar",
        duracionSeg: 203,
        resumen:
          "Perdió el trabajo hace dos meses. Puede abonar 200 dólares mensuales, no los 422.50. Pidió que le manden opciones de refinanciamiento.",
        transcript:
          "Agente: Buenas tardes, le saluda Camila, del área de servicio al cliente de Banco Promerica. ¿Hablo con Rosa Elena Portillo?\nCliente: Sí, soy yo.\nAgente: Por seguridad, ¿me confirma su fecha de nacimiento?\nCliente: Doce de marzo del setenta y nueve.\nAgente: Gracias, doña Rosa. Le llamo por su préstamo personal, que tiene ochocientos cuarenta y cinco dólares pendientes con sesenta y dos días de atraso.\nCliente: Mire, yo sé. Es que me quedé sin trabajo en junio. Yo no me estoy escondiendo, lo que pasa es que no tengo de dónde.\nAgente: Entiendo, doña Rosa. ¿Qué sí podría abonar y cuándo?\nCliente: Yo podría hacerle unos doscientos al mes mientras me acomodo, pero los cuatrocientos veintidós no me dan.\nAgente: Le entiendo. Eso lo revisa un asesor, con gusto le agendo que la llamen para ver opciones.\nCliente: Sí, por favor, que me llamen. Yo quiero arreglar esto.\nAgente: Perfecto. Gracias por contestar, doña Rosa. Que esté bien.",
      },
      {
        id: "g2b",
        tipo: "nota",
        cuando: dias(10),
        autor: "gestor",
        resumen: "Cliente reportó cambio de empleo. Se reprogramó gestión para agosto.",
      },
    ],
  },
  {
    id: "d3",
    nombre: "Carlos Ernesto Sibrián",
    documento: "0455****-8",
    telefono: "+50372338814",
    producto: "auto",
    cuenta: "****1178",
    saldoTotal: 11250.0,
    montoVencido: 1490.0,
    cuotaMensual: 372.5,
    diasMora: 118,
    ultimoPago: { fecha: fecha(130), monto: 372.5 },
    estado: "promesa_rota",
    riesgo: "alto",
    sentimiento: "evasivo",
    promesa: { monto: 745.0, fecha: fecha(9), registrada: dias(23), origen: "ia", cumplida: false },
    proximaAccion: { tipo: "escalar_humano", nota: "Tercera promesa incumplida." },
    resumenIa:
      "Prometió abonar 745 el 8 de agosto y no lo hizo. Es la tercera promesa que no cumple. Evita dar fecha nueva.",
    etiquetas: ["Promesa rota x3"],
    llamable: true,
    actualizado: dias(4),
    gestiones: [
      {
        id: "g3",
        tipo: "llamada",
        cuando: dias(4),
        autor: "ia",
        resultado: "pidio_recontacto",
        duracionSeg: 61,
        resumen: "Dijo que estaba manejando y que le llamaran después. No dio fecha ni monto.",
      },
      {
        id: "g3b",
        tipo: "llamada",
        cuando: dias(23),
        autor: "ia",
        resultado: "promesa_pago",
        duracionSeg: 132,
        resumen: "Prometió abonar 745 dólares el 8 de agosto.",
      },
    ],
  },
  {
    id: "d4",
    nombre: "Marielos Guzmán Arévalo",
    documento: "0512****-3",
    telefono: "+50361611519",
    producto: "tarjeta",
    cuenta: "****2260",
    saldoTotal: 940.0,
    montoVencido: 188.0,
    cuotaMensual: 94.0,
    diasMora: 12,
    ultimoPago: { fecha: fecha(28), monto: 94.0 },
    estado: "sin_gestionar",
    riesgo: "bajo",
    etiquetas: [],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
  {
    id: "d5",
    nombre: "Herman Portillo Guevara",
    documento: "0611****-5",
    telefono: "+50322503300",
    producto: "pyme",
    cuenta: "****7714",
    saldoTotal: 28400.0,
    montoVencido: 4260.0,
    cuotaMensual: 1420.0,
    diasMora: 94,
    ultimoPago: { fecha: fecha(102), monto: 1420.0 },
    estado: "disputa",
    riesgo: "alto",
    sentimiento: "molesto",
    proximaAccion: { tipo: "escalar_humano", nota: "Reclama cobro de seguro no contratado." },
    resumenIa:
      "Reclama que le están cobrando un seguro que dice que nunca contrató. Pidió estado de cuenta detallado antes de pagar.",
    etiquetas: ["Reclamo abierto", "Revisar"],
    llamable: true,
    actualizado: dias(6),
    gestiones: [
      {
        id: "g5",
        tipo: "llamada",
        cuando: dias(6),
        autor: "ia",
        resultado: "disputa",
        duracionSeg: 245,
        resumen:
          "Reclama que le están cobrando un seguro que dice que nunca contrató. Pidió estado de cuenta detallado antes de pagar.",
      },
    ],
  },
  {
    id: "d6",
    nombre: "Wendy Carolina Ramos",
    documento: "0723****-9",
    telefono: "+50360557788",
    producto: "prestamo_personal",
    cuenta: "****3391",
    saldoTotal: 2180.0,
    montoVencido: 218.0,
    cuotaMensual: 218.0,
    diasMora: 22,
    ultimoPago: { fecha: fecha(52), monto: 218.0 },
    estado: "pagado",
    riesgo: "bajo",
    sentimiento: "cooperativo",
    proximaAccion: { tipo: "cerrar" },
    resumenIa: "Dice que pagó el 14 por banca en línea. Queda pendiente que el banco lo verifique.",
    etiquetas: ["Verificar pago"],
    llamable: false,
    actualizado: dias(2),
    gestiones: [
      {
        id: "g6",
        tipo: "llamada",
        cuando: dias(2),
        autor: "ia",
        resultado: "ya_pago",
        duracionSeg: 74,
        resumen: "Dice que pagó el 14 por banca en línea. Queda pendiente que el banco lo verifique.",
      },
    ],
  },
  {
    id: "d7",
    nombre: "Douglas Antonio Menjívar",
    documento: "0834****-2",
    telefono: "+50379334412",
    producto: "vivienda",
    cuenta: "****8820",
    saldoTotal: 64800.0,
    montoVencido: 1890.0,
    cuotaMensual: 630.0,
    diasMora: 71,
    ultimoPago: { fecha: fecha(84), monto: 630.0 },
    estado: "en_gestion",
    riesgo: "medio",
    etiquetas: [],
    llamable: true,
    actualizado: dias(5),
    gestiones: [
      {
        id: "g7",
        tipo: "llamada",
        cuando: dias(5),
        autor: "ia",
        resultado: "no_contesto",
        duracionSeg: 0,
        resumen: "No contestó.",
      },
      {
        id: "g7b",
        tipo: "llamada",
        cuando: dias(8),
        autor: "ia",
        resultado: "no_contesto",
        duracionSeg: 0,
        resumen: "No contestó.",
      },
    ],
  },
  {
    id: "d8",
    nombre: "Sandra Beatriz Melgar",
    documento: "0945****-6",
    telefono: "+50376113420",
    producto: "tarjeta",
    cuenta: "****5503",
    saldoTotal: 3120.0,
    montoVencido: 624.0,
    cuotaMensual: 312.0,
    diasMora: 47,
    ultimoPago: { fecha: fecha(60), monto: 312.0 },
    estado: "pago_parcial",
    riesgo: "medio",
    sentimiento: "cooperativo",
    promesa: { monto: 312.0, fecha: fecha(-6), registrada: dias(7), origen: "ia" },
    proximaAccion: { tipo: "recontactar", cuando: fecha(-6) },
    resumenIa: "Abonó 312 el 10 de agosto y quedó de completar el resto a fin de mes.",
    etiquetas: ["Abono parcial"],
    llamable: true,
    actualizado: dias(7),
    gestiones: [
      {
        id: "g8",
        tipo: "pago",
        cuando: dias(7),
        autor: "sistema",
        resumen: "Abonó $312.00 por banca en línea.",
      },
      {
        id: "g8b",
        tipo: "llamada",
        cuando: dias(9),
        autor: "ia",
        resultado: "pago_parcial",
        duracionSeg: 118,
        resumen: "Puede abonar la mitad ahora y el resto a fin de mes.",
      },
    ],
  },
  {
    id: "d9",
    nombre: "Óscar Iraheta Bonilla",
    documento: "1056****-4",
    telefono: "+50372560091",
    producto: "auto",
    cuenta: "****6647",
    saldoTotal: 8930.0,
    montoVencido: 2680.0,
    cuotaMensual: 335.0,
    diasMora: 156,
    ultimoPago: { fecha: fecha(170), monto: 335.0 },
    estado: "legal",
    riesgo: "alto",
    proximaAccion: { tipo: "escalar_legal", nota: "Más de 150 días sin pago ni contacto." },
    etiquetas: ["Legal"],
    llamable: false,
    actualizado: dias(14),
    gestiones: [
      {
        id: "g9",
        tipo: "sistema",
        cuando: dias(14),
        autor: "sistema",
        resumen: "Cuenta trasladada al área legal por mora mayor a 150 días.",
      },
    ],
  },
  {
    id: "d10",
    nombre: "Karla Vanessa Bonilla",
    documento: "1167****-0",
    telefono: "+50370125566",
    producto: "tarjeta",
    cuenta: "****1194",
    saldoTotal: 620.0,
    montoVencido: 124.0,
    cuotaMensual: 62.0,
    diasMora: 8,
    ultimoPago: { fecha: fecha(30), monto: 62.0 },
    estado: "sin_gestionar",
    riesgo: "bajo",
    etiquetas: [],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
  {
    id: "d11",
    nombre: "Nelson Adalberto Cruz",
    documento: "1278****-8",
    telefono: "+50371193358",
    producto: "prestamo_personal",
    cuenta: "****4408",
    saldoTotal: 4750.0,
    montoVencido: 950.0,
    cuotaMensual: 475.0,
    diasMora: 58,
    ultimoPago: { fecha: fecha(70), monto: 475.0 },
    estado: "no_contactar",
    riesgo: "alto",
    sentimiento: "molesto",
    proximaAccion: { tipo: "sacar_de_campana", nota: "Pidió expresamente que no lo llamen." },
    resumenIa:
      "Pidió que no lo vuelvan a llamar por teléfono. Dijo que solo acepta comunicación por escrito.",
    etiquetas: ["No llamar", "Revisar"],
    llamable: false,
    actualizado: dias(11),
    gestiones: [
      {
        id: "g11",
        tipo: "llamada",
        cuando: dias(11),
        autor: "ia",
        resultado: "solicita_no_llamar",
        duracionSeg: 43,
        resumen:
          "Pidió que no lo vuelvan a llamar por teléfono. Dijo que solo acepta comunicación por escrito.",
      },
    ],
  },
  {
    id: "d12",
    nombre: "Fátima Argueta de Rivas",
    documento: "1389****-1",
    telefono: "+50378204455",
    producto: "tarjeta",
    cuenta: "****7726",
    saldoTotal: 1490.0,
    montoVencido: 298.0,
    cuotaMensual: 149.0,
    diasMora: 29,
    ultimoPago: { fecha: fecha(44), monto: 149.0 },
    estado: "ilocalizable",
    riesgo: "alto",
    proximaAccion: { tipo: "sacar_de_campana", nota: "El número es de otra persona." },
    resumenIa: "El número ya no le pertenece. Contestó una persona que no la conoce.",
    etiquetas: ["Número equivocado"],
    llamable: false,
    actualizado: dias(9),
    gestiones: [
      {
        id: "g12",
        tipo: "llamada",
        cuando: dias(9),
        autor: "ia",
        resultado: "numero_equivocado",
        duracionSeg: 22,
        resumen: "El número ya no le pertenece. Contestó una persona que no la conoce.",
      },
    ],
  },
  {
    id: "d13",
    nombre: "Rodrigo Escalante Vides",
    documento: "1490****-7",
    telefono: "+50375391721",
    producto: "pyme",
    cuenta: "****3352",
    saldoTotal: 17600.0,
    montoVencido: 2200.0,
    cuotaMensual: 1100.0,
    diasMora: 41,
    ultimoPago: { fecha: fecha(55), monto: 1100.0 },
    estado: "en_gestion",
    riesgo: "medio",
    etiquetas: ["Cliente PYME"],
    llamable: true,
    actualizado: dias(3),
    gestiones: [
      {
        id: "g13",
        tipo: "llamada",
        cuando: dias(3),
        autor: "ia",
        resultado: "contesto_tercero",
        duracionSeg: 31,
        resumen: "Contestó la secretaria. Dijo que el titular llega después de las dos de la tarde.",
      },
    ],
  },
  {
    id: "d14",
    nombre: "Xiomara Cruz de Peña",
    documento: "1502****-5",
    telefono: "+50374882031",
    producto: "vivienda",
    cuenta: "****9967",
    saldoTotal: 42300.0,
    montoVencido: 1150.0,
    cuotaMensual: 575.0,
    diasMora: 38,
    ultimoPago: { fecha: fecha(50), monto: 575.0 },
    estado: "promesa_pago",
    riesgo: "bajo",
    sentimiento: "cooperativo",
    promesa: { monto: 1150.0, fecha: fecha(-8), registrada: dias(4), origen: "gestor" },
    proximaAccion: { tipo: "esperar_pago", cuando: fecha(-8) },
    etiquetas: [],
    llamable: true,
    actualizado: dias(4),
    gestiones: [
      {
        id: "g14",
        tipo: "nota",
        cuando: dias(4),
        autor: "gestor",
        resumen: "Llamó ella al call center. Quedó de pagar las dos cuotas el 25.",
      },
    ],
  },
  {
    id: "d15",
    nombre: "Julio César Barahona",
    documento: "1613****-2",
    telefono: "+50377340192",
    producto: "prestamo_personal",
    cuenta: "****2205",
    saldoTotal: 3400.0,
    montoVencido: 1700.0,
    cuotaMensual: 425.0,
    diasMora: 122,
    ultimoPago: { fecha: fecha(135), monto: 425.0 },
    estado: "en_gestion",
    riesgo: "alto",
    sentimiento: "evasivo",
    proximaAccion: { tipo: "recontactar", cuando: fecha(-2) },
    resumenIa: "Dijo que no puede pagar nada este mes. No dio fecha ni monto alternativo.",
    etiquetas: [],
    llamable: true,
    actualizado: dias(6),
    gestiones: [
      {
        id: "g15",
        tipo: "llamada",
        cuando: dias(6),
        autor: "ia",
        resultado: "no_puede_pagar",
        duracionSeg: 96,
        resumen: "Dijo que no puede pagar nada este mes. No dio fecha ni monto alternativo.",
      },
    ],
  },
  {
    id: "d16",
    nombre: "Andrea Sosa Recinos",
    documento: "1724****-9",
    telefono: "+50362117744",
    producto: "tarjeta",
    cuenta: "****6018",
    saldoTotal: 2260.0,
    montoVencido: 452.0,
    cuotaMensual: 226.0,
    diasMora: 51,
    ultimoPago: { fecha: fecha(66), monto: 226.0 },
    estado: "sin_gestionar",
    riesgo: "medio",
    etiquetas: [],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
  {
    id: "d17",
    nombre: "Mauricio Alexander Rivas",
    documento: "1835****-3",
    telefono: "+50379908812",
    producto: "auto",
    cuenta: "****4432",
    saldoTotal: 14900.0,
    montoVencido: 596.0,
    cuotaMensual: 298.0,
    diasMora: 26,
    ultimoPago: { fecha: fecha(41), monto: 298.0 },
    estado: "sin_gestionar",
    riesgo: "bajo",
    etiquetas: [],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
  {
    id: "d18",
    nombre: "Gabriela Menéndez Sol",
    documento: "1946****-6",
    telefono: "+50376620045",
    producto: "prestamo_personal",
    cuenta: "****8871",
    saldoTotal: 5600.0,
    montoVencido: 1400.0,
    cuotaMensual: 350.0,
    diasMora: 87,
    ultimoPago: { fecha: fecha(98), monto: 350.0 },
    estado: "en_gestion",
    riesgo: "alto",
    etiquetas: [],
    llamable: true,
    actualizado: dias(12),
    gestiones: [
      {
        id: "g18",
        tipo: "llamada",
        cuando: dias(12),
        autor: "ia",
        resultado: "colgo",
        duracionSeg: 14,
        resumen: "Colgó apenas se identificó el banco.",
      },
    ],
  },
  {
    id: "d19",
    nombre: "Ernesto Alfredo Quintanilla",
    documento: "2057****-4",
    telefono: "+50371450098",
    producto: "pyme",
    cuenta: "****5540",
    saldoTotal: 33200.0,
    montoVencido: 830.0,
    cuotaMensual: 830.0,
    diasMora: 17,
    ultimoPago: { fecha: fecha(32), monto: 830.0 },
    estado: "sin_gestionar",
    riesgo: "bajo",
    etiquetas: ["Cliente PYME"],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
  {
    id: "d20",
    nombre: "Silvia Lorena Cáceres",
    documento: "2168****-8",
    telefono: "+50378112360",
    producto: "tarjeta",
    cuenta: "****3084",
    saldoTotal: 780.0,
    montoVencido: 390.0,
    cuotaMensual: 78.0,
    diasMora: 103,
    ultimoPago: { fecha: fecha(118), monto: 78.0 },
    estado: "en_gestion",
    riesgo: "alto",
    etiquetas: [],
    llamable: true,
    actualizado: dias(13),
    gestiones: [
      {
        id: "g20",
        tipo: "llamada",
        cuando: dias(13),
        autor: "ia",
        resultado: "no_contesto",
        duracionSeg: 0,
        resumen: "No contestó.",
      },
    ],
  },
  {
    id: "d21",
    nombre: "Jorge Alberto Henríquez",
    documento: "2279****-0",
    telefono: "+50370338826",
    producto: "vivienda",
    cuenta: "****7712",
    saldoTotal: 51800.0,
    montoVencido: 2760.0,
    cuotaMensual: 690.0,
    diasMora: 132,
    ultimoPago: { fecha: fecha(146), monto: 690.0 },
    estado: "negociacion",
    riesgo: "alto",
    sentimiento: "cooperativo",
    proximaAccion: { tipo: "enviar_convenio", cuando: fecha(-3) },
    resumenIa:
      "Está dispuesto a firmar convenio. Pidió que le expliquen cómo queda la cuota antes de comprometerse.",
    etiquetas: ["Pide convenio"],
    llamable: true,
    actualizado: dias(8),
    gestiones: [
      {
        id: "g21",
        tipo: "llamada",
        cuando: dias(8),
        autor: "ia",
        resultado: "quiere_negociar",
        duracionSeg: 187,
        resumen:
          "Está dispuesto a firmar convenio. Pidió que le expliquen cómo queda la cuota antes de comprometerse.",
      },
    ],
  },
  {
    id: "d22",
    nombre: "Claudia Patricia Alfaro",
    documento: "2380****-7",
    telefono: "+50376990412",
    producto: "tarjeta",
    cuenta: "****2298",
    saldoTotal: 1120.0,
    montoVencido: 224.0,
    cuotaMensual: 112.0,
    diasMora: 19,
    ultimoPago: { fecha: fecha(34), monto: 112.0 },
    estado: "sin_gestionar",
    riesgo: "bajo",
    etiquetas: [],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
  {
    id: "d23",
    nombre: "Víctor Manuel Escobar",
    documento: "2491****-5",
    telefono: "+50372208831",
    producto: "auto",
    cuenta: "****6693",
    saldoTotal: 9700.0,
    montoVencido: 1164.0,
    cuotaMensual: 388.0,
    diasMora: 79,
    ultimoPago: { fecha: fecha(92), monto: 388.0 },
    estado: "en_gestion",
    riesgo: "medio",
    etiquetas: [],
    llamable: true,
    actualizado: dias(10),
    gestiones: [
      {
        id: "g23",
        tipo: "llamada",
        cuando: dias(10),
        autor: "ia",
        resultado: "pidio_recontacto",
        duracionSeg: 52,
        resumen: "Pidió que le llamen el lunes por la tarde.",
      },
    ],
  },
  {
    id: "d24",
    nombre: "Nadia Beatriz Quintanilla",
    documento: "2502****-2",
    telefono: "+50378845507",
    producto: "prestamo_personal",
    cuenta: "****1140",
    saldoTotal: 2900.0,
    montoVencido: 290.0,
    cuotaMensual: 290.0,
    diasMora: 15,
    ultimoPago: { fecha: fecha(30), monto: 290.0 },
    estado: "sin_gestionar",
    riesgo: "bajo",
    etiquetas: [],
    llamable: true,
    actualizado: dias(1),
    gestiones: [],
  },
];

export const HOY_DEMO = HOY;
