// Cartera y leads de demostración de Terrazul Bienes Raíces.
//
// TODO es inventado: personas, propietarios, códigos y direcciones. Los precios
// y las zonas sí siguen el mercado salvadoreño para que el tablero se lea como
// el de una inmobiliaria de verdad. Las fotos viven en public/inmobiliaria (ver
// scripts/bajar-fotos-inmobiliaria.mjs) y son de banco de imágenes: en el demo
// nunca va la foto de una propiedad que existe, y ninguna se genera con IA.
//
// Los tiempos van en RELATIVO (`hace`, `exclusivaEnDias`, `mudanzaEnDias`) y se
// resuelven contra el día en que se abre el tablero, así el demo no envejece.
//
// Hay cartera y leads de VENTA y de ALQUILER. En alquiler el precio y el
// presupuesto son MENSUALES: nunca se suman con los de venta.

import type { Ambiente, Foto, LeadSemilla, PropiedadSemilla } from "./inmobiliaria-tipos";

function fotos(codigo: string, ambientes: Ambiente[]): Foto[] {
  return ambientes.map((ambiente, i) => ({
    src: `/inmobiliaria/${codigo}-${i + 1}.jpg`,
    ambiente,
    ancho: 1080,
    alto: 810,
  }));
}

export const ASESORES = [
  { id: "me", nombre: "Gerente Comercial", iniciales: "GC" },
  { id: "s2", nombre: "Alejandra Portillo", iniciales: "AP" },
  { id: "s3", nombre: "Douglas Menjívar", iniciales: "DM" },
  { id: "s4", nombre: "Karla Bonilla", iniciales: "KB" },
  { id: "s5", nombre: "Rodrigo Escalante", iniciales: "RE" },
];

export const PROPIEDADES: PropiedadSemilla[] = [
  {
    id: "p1",
    codigo: "TZ-101",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa de dos niveles en Colonia Escalón",
    zona: "Colonia Escalón",
    municipio: "San Salvador",
    precio: 425000,
    estado: "disponible",
    publicada: true,
    habitaciones: 4,
    banos: 4,
    parqueos: 3,
    areaConstruccion: 380,
    areaTerreno: 420,
    anio: 2012,
    propietario: { nombre: "Ricardo Alvarenga Mejía", telefono: "+503 7412 8890" },
    exclusiva: true,
    exclusivaEnDias: 110,
    caracteristicas: [
      "Habitación principal con vestidor y baño propio",
      "Estudio independiente en planta baja",
      "Cocina con isla y despensa",
      "Cisterna y planta eléctrica",
      "Portón eléctrico",
    ],
    resumen:
      "Casa amplia en una de las zonas más buscadas de San Salvador, lista para entrar a vivir.",
    fotos: fotos("tz-101", ["sala", "fachada", "cocina", "habitacion"]),
  },
  {
    id: "p2",
    codigo: "TZ-102",
    operacion: "venta",
    tipo: "apartamento",
    titulo: "Apartamento en torre con vista, Zona Rosa",
    zona: "Zona Rosa",
    municipio: "San Salvador",
    precio: 265000,
    estado: "disponible",
    publicada: true,
    habitaciones: 2,
    banos: 2,
    parqueos: 2,
    areaConstruccion: 145,
    areaTerreno: 0,
    anio: 2019,
    propietario: { nombre: "Silvia Menéndez de Portillo", telefono: "+503 7830 4417" },
    exclusiva: true,
    exclusivaEnDias: 24,
    caracteristicas: [
      "Piso 9 con balcón",
      "Seguridad 24 horas",
      "Piscina, gimnasio y área social en el edificio",
      "Cuota de mantenimiento incluida el primer año",
    ],
    resumen: "Apartamento a pie de restaurantes y oficinas, ideal para quien no quiere manejar.",
    fotos: fotos("tz-102", ["sala", "cocina", "habitacion", "fachada", "patio"]),
  },
  {
    id: "p3",
    codigo: "TZ-103",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa en residencial cerrado, Santa Tecla",
    zona: "Residencial Las Colinas",
    municipio: "Santa Tecla",
    precio: 198000,
    estado: "apartada",
    publicada: true,
    habitaciones: 3,
    banos: 3,
    parqueos: 2,
    areaConstruccion: 165,
    areaTerreno: 210,
    anio: 2016,
    propietario: { nombre: "Familia Recinos Ayala", telefono: "+503 7255 6031" },
    exclusiva: false,
    caracteristicas: [
      "Residencial con caseta y garita",
      "Patio con jardín al fondo",
      "Cuarto de servicio con baño",
      "Calle interna adoquinada",
    ],
    resumen: "Casa en residencial tranquilo, a diez minutos del centro de Santa Tecla.",
    fotos: fotos("tz-103", ["fachada", "sala", "cocina", "patio"]),
  },
  {
    id: "p4",
    codigo: "TZ-104",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa remodelada en Jardines de Merliot",
    zona: "Jardines de Merliot",
    municipio: "Antiguo Cuscatlán",
    precio: 172500,
    estado: "disponible",
    publicada: true,
    habitaciones: 3,
    banos: 2,
    parqueos: 2,
    areaConstruccion: 140,
    areaTerreno: 175,
    anio: 2004,
    propietario: { nombre: "Mauricio Cañas Regalado", telefono: "+503 7008 2264" },
    exclusiva: false,
    caracteristicas: [
      "Cocina y baños remodelados este año",
      "Piso de porcelanato en toda la casa",
      "Terraza techada",
      "Cerca de centros comerciales y colegios",
    ],
    resumen: "Casa recién remodelada, con la papelería al día y lista para escriturar.",
    fotos: fotos("tz-104", ["cocina", "sala", "habitacion"]),
  },
  {
    id: "p5",
    codigo: "TZ-105",
    operacion: "venta",
    tipo: "terreno",
    titulo: "Terreno con vista al mar, carretera al Litoral",
    zona: "Km 39 carretera al Litoral",
    municipio: "La Libertad",
    precio: 118000,
    estado: "disponible",
    publicada: true,
    habitaciones: 0,
    banos: 0,
    parqueos: 0,
    areaConstruccion: 0,
    areaTerreno: 850,
    propietario: { nombre: "Gloria Beatriz Sandoval", telefono: "+503 7644 9012" },
    exclusiva: true,
    exclusivaEnDias: 156,
    caracteristicas: [
      "Acceso por calle de asfalto",
      "Agua y electricidad en la entrada",
      "Escritura inscrita y libre de gravamen",
      "Plano topográfico levantado",
    ],
    resumen: "Terreno plano con vista abierta al mar, a cinco minutos de la playa.",
    fotos: fotos("tz-105", ["terreno", "terreno", "terreno"]),
  },
  {
    id: "p6",
    codigo: "TZ-106",
    operacion: "venta",
    tipo: "local",
    titulo: "Local comercial sobre paseo peatonal, Santa Tecla",
    zona: "Paseo El Carmen",
    municipio: "Santa Tecla",
    precio: 245000,
    estado: "disponible",
    publicada: true,
    habitaciones: 0,
    banos: 2,
    parqueos: 3,
    areaConstruccion: 190,
    areaTerreno: 220,
    anio: 2009,
    propietario: { nombre: "Herman Portillo Guevara", telefono: "+503 7119 3358" },
    exclusiva: false,
    caracteristicas: [
      "Frente sobre el paseo, con vitrina",
      "Bodega y baño de personal al fondo",
      "Trifásico instalado",
      "Permiso de rótulo vigente",
    ],
    resumen: "Local a pie de calle en la zona de mayor paso peatonal de Santa Tecla.",
    fotos: fotos("tz-106", ["local", "local", "bano"]),
  },
  {
    id: "p7",
    codigo: "TZ-107",
    operacion: "venta",
    tipo: "apartamento",
    titulo: "Apartamento en Santa Elena",
    zona: "Santa Elena",
    municipio: "Antiguo Cuscatlán",
    precio: 158000,
    estado: "vendida",
    publicada: true,
    habitaciones: 2,
    banos: 2,
    parqueos: 1,
    areaConstruccion: 96,
    areaTerreno: 0,
    anio: 2015,
    propietario: { nombre: "Karla Nájera Cortez", telefono: "+503 7523 7781" },
    exclusiva: false,
    caracteristicas: ["Tercer nivel", "Área social con piscina", "Bodega privada"],
    resumen: "Apartamento cómodo en zona de oficinas, con área social del condominio.",
    fotos: fotos("tz-107", ["sala", "habitacion", "bano"]),
  },
  {
    id: "p8",
    codigo: "TZ-108",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa en Lourdes, apta para crédito FSV",
    zona: "Lourdes",
    municipio: "Colón",
    precio: 76500,
    estado: "disponible",
    publicada: true,
    habitaciones: 3,
    banos: 2,
    parqueos: 1,
    areaConstruccion: 78,
    areaTerreno: 105,
    anio: 2018,
    propietario: { nombre: "José Roberto Cruz Handal", telefono: "+503 7381 5520" },
    exclusiva: false,
    caracteristicas: [
      "Dentro del tope de precio del FSV",
      "Escritura inscrita a nombre del propietario",
      "Portón y muro perimetral",
      "Transporte a la entrada del residencial",
    ],
    resumen: "Casa que califica para crédito del Fondo Social, con papelería en regla.",
    fotos: fotos("tz-108", ["sala", "habitacion"]),
  },
  {
    id: "p9",
    codigo: "TZ-109",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa con jardín en Nuevo Cuscatlán",
    zona: "Residencial Altos del Bosque",
    municipio: "Nuevo Cuscatlán",
    precio: 348000,
    estado: "disponible",
    publicada: true,
    habitaciones: 4,
    banos: 4,
    parqueos: 3,
    areaConstruccion: 290,
    areaTerreno: 380,
    anio: 2020,
    propietario: { nombre: "Ana Cecilia Menjívar Alfaro", telefono: "+503 7266 8845" },
    exclusiva: true,
    exclusivaEnDias: -12,
    caracteristicas: [
      "Jardín amplio con terraza",
      "Habitación principal en planta baja",
      "Paneles solares instalados",
      "Clima fresco todo el año",
    ],
    resumen: "Casa nueva con jardín grande, en la zona de mejor clima del área metropolitana.",
    fotos: fotos("tz-109", ["fachada", "patio", "sala", "cocina", "habitacion"]),
  },
  {
    id: "p10",
    codigo: "TZ-110",
    operacion: "venta",
    tipo: "apartamento",
    titulo: "Apartamento en torre sobre Escalón",
    zona: "Colonia Escalón",
    municipio: "San Salvador",
    precio: 215000,
    estado: "apartada",
    publicada: false,
    habitaciones: 3,
    banos: 2,
    parqueos: 2,
    areaConstruccion: 128,
    areaTerreno: 0,
    anio: 2017,
    propietario: { nombre: "Edgardo Villalta Sosa", telefono: "+503 7940 1176" },
    exclusiva: false,
    caracteristicas: ["Piso 5 con balcón", "Dos parqueos techados", "Planta eléctrica del edificio"],
    resumen: "Apartamento sobre la avenida principal, con dos parqueos techados.",
    fotos: fotos("tz-110", ["sala", "cocina", "habitacion", "bano"]),
  },
  {
    id: "p11",
    codigo: "TZ-111",
    operacion: "venta",
    tipo: "terreno",
    titulo: "Terreno urbano en Las Delicias",
    zona: "Las Delicias",
    municipio: "Santa Tecla",
    precio: 89000,
    estado: "disponible",
    publicada: true,
    habitaciones: 0,
    banos: 0,
    parqueos: 0,
    areaConstruccion: 0,
    areaTerreno: 620,
    propietario: { nombre: "Marta Alicia Rivas Zelaya", telefono: "+503 7702 4489" },
    exclusiva: false,
    caracteristicas: [
      "Servicios instalados en la acera",
      "Uso de suelo habitacional",
      "Calle pavimentada",
    ],
    resumen: "Terreno urbano listo para construir, con todos los servicios en la acera.",
    fotos: fotos("tz-111", ["terreno", "terreno"]),
  },
  {
    id: "p12",
    codigo: "TZ-112",
    operacion: "venta",
    tipo: "casa",
    titulo: "Casa amplia en Colonia Layco",
    zona: "Colonia Layco",
    municipio: "San Salvador",
    precio: 92000,
    estado: "disponible",
    publicada: true,
    habitaciones: 3,
    banos: 2,
    parqueos: 2,
    areaConstruccion: 120,
    areaTerreno: 160,
    anio: 1988,
    propietario: { nombre: "Óscar Arévalo Pineda", telefono: "+503 7455 9028" },
    exclusiva: false,
    caracteristicas: [
      "Interior remodelado, fachada pendiente",
      "Techo cambiado hace tres años",
      "Zona con comercio y transporte",
    ],
    resumen:
      "Casa de buen tamaño para vivir o para renta, con el interior renovado y la fachada por trabajar.",
    fotos: fotos("tz-112", ["fachada", "sala", "cocina", "patio"]),
  },

  // ── En alquiler ──
  // El precio de estas es MENSUAL. Además llevan depósito y plazo mínimo, que
  // son las dos preguntas que llegan por WhatsApp antes que cualquier otra.
  {
    id: "p13",
    codigo: "TZ-113",
    operacion: "alquiler",
    tipo: "apartamento",
    titulo: "Apartamento amueblado en Santa Elena",
    zona: "Santa Elena",
    municipio: "Antiguo Cuscatlán",
    precio: 750,
    deposito: 750,
    plazoMinimoMeses: 12,
    estado: "disponible",
    publicada: true,
    habitaciones: 2,
    banos: 2,
    parqueos: 1,
    areaConstruccion: 92,
    areaTerreno: 0,
    anio: 2018,
    propietario: { nombre: "Lorena Escobar de Quintanilla", telefono: "+503 7318 9042" },
    exclusiva: true,
    exclusivaEnDias: 74,
    caracteristicas: [
      "Entra amueblado y con electrodomésticos",
      "Agua y vigilancia incluidas en la renta",
      "Un parqueo techado asignado",
      "A cinco minutos de las oficinas de Santa Elena",
    ],
    resumen:
      "Apartamento listo para entrar con maletas, en zona de oficinas y con vigilancia las 24 horas.",
    fotos: fotos("tz-113", ["sala", "habitacion", "bano"]),
  },
  {
    id: "p14",
    codigo: "TZ-114",
    operacion: "alquiler",
    tipo: "casa",
    titulo: "Casa en residencial con garita, Santa Tecla",
    zona: "Residencial Villas de Ávila",
    municipio: "Santa Tecla",
    precio: 950,
    deposito: 1900,
    plazoMinimoMeses: 12,
    estado: "disponible",
    publicada: true,
    habitaciones: 3,
    banos: 3,
    parqueos: 2,
    areaConstruccion: 175,
    areaTerreno: 220,
    anio: 2014,
    propietario: { nombre: "Rafael Antonio Guirola", telefono: "+503 7885 3327" },
    exclusiva: true,
    exclusivaEnDias: 18,
    caracteristicas: [
      "Residencial con garita y vigilancia",
      "Patio con terraza techada",
      "Cocina con pantry y desayunador",
      "Se acepta una mascota pequeña",
    ],
    resumen:
      "Casa familiar en residencial cerrado, con patio y dos parqueos, a diez minutos del centro de Santa Tecla.",
    fotos: fotos("tz-114", ["sala", "fachada", "cocina", "patio"]),
  },
  {
    id: "p15",
    codigo: "TZ-115",
    operacion: "alquiler",
    tipo: "local",
    titulo: "Local sobre Paseo General Escalón",
    zona: "Colonia Escalón",
    municipio: "San Salvador",
    precio: 1250,
    deposito: 2500,
    plazoMinimoMeses: 24,
    estado: "disponible",
    publicada: true,
    habitaciones: 0,
    banos: 1,
    parqueos: 2,
    areaConstruccion: 110,
    areaTerreno: 0,
    anio: 2011,
    propietario: { nombre: "Inmuebles La Cima, S.A. de C.V.", telefono: "+503 2264 7719" },
    exclusiva: false,
    caracteristicas: [
      "Vitrina completa sobre el paseo",
      "Dos parqueos al frente para clientes",
      "Aire acondicionado instalado",
      "Se entrega en obra gris o terminado, a convenir",
    ],
    resumen:
      "Local a pie de calle sobre una de las avenidas de mayor tráfico de San Salvador, con parqueo al frente.",
    fotos: fotos("tz-115", ["local", "local"]),
  },
  {
    id: "p16",
    codigo: "TZ-116",
    operacion: "alquiler",
    tipo: "apartamento",
    titulo: "Apartamento de una habitación en Escalón",
    zona: "Colonia Escalón",
    municipio: "San Salvador",
    precio: 525,
    deposito: 525,
    plazoMinimoMeses: 6,
    // Ya se alquiló y sigue publicada: la misma alerta cara de la venta, pero
    // con la palabra del alquiler.
    estado: "vendida",
    publicada: true,
    habitaciones: 1,
    banos: 1,
    parqueos: 1,
    areaConstruccion: 62,
    areaTerreno: 0,
    anio: 2016,
    propietario: { nombre: "Ligia Marisol Peña", telefono: "+503 7093 6614" },
    exclusiva: false,
    caracteristicas: ["Cuarto piso con balcón", "Cisterna del edificio", "Un parqueo asignado"],
    resumen: "Apartamento de una habitación sobre Escalón, cómodo para una persona o una pareja.",
    fotos: fotos("tz-116", ["sala", "habitacion"]),
  },
];

export const LEADS: LeadSemilla[] = [
  // ── Nuevos ──
  {
    id: "l1",
    nombre: "Wendy Carolina Ramos",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "nuevo",
    formaPago: "sin_definir",
    presupuesto: 120000,
    zona: "Santa Tecla",
    busca: "Casa de 3 habitaciones",
    hace: 0,
    asesorId: "s2",
    nota: "Escribió por el anuncio de TZ-103.",
    propiedadId: "p3",
  },
  {
    id: "l2",
    nombre: "Julio César Barahona",
    canal: "messenger",
    operacion: "venta",
    etapa: "nuevo",
    formaPago: "banco",
    presupuesto: 185000,
    zona: "Antiguo Cuscatlán",
    busca: "Casa en residencial cerrado",
    hace: 1,
    asesorId: "s3",
    propiedadId: "p4",
  },
  {
    id: "l3",
    nombre: "Marielos Guzmán",
    canal: "instagram",
    operacion: "venta",
    etapa: "nuevo",
    formaPago: "sin_definir",
    presupuesto: 80000,
    zona: "La Libertad",
    busca: "Casa cerca de Lourdes",
    hace: 2,
    asesorId: "s4",
    propiedadId: "p8",
  },
  {
    id: "l4",
    nombre: "Nelson Amaya Cruz",
    canal: "comentario",
    operacion: "venta",
    etapa: "nuevo",
    formaPago: "sin_definir",
    presupuesto: 95000,
    zona: "San Salvador",
    busca: "Casa en zona céntrica",
    hace: 4,
    asesorId: "s2",
    nota: "Comentó en la publicación de TZ-112 y no ha respondido el mensaje.",
    propiedadId: "p12",
  },
  {
    id: "l5",
    nombre: "Gabriela Hernández",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "nuevo",
    formaPago: "contado",
    presupuesto: 130000,
    zona: "La Libertad",
    busca: "Terreno con vista al mar",
    hace: 1,
    asesorId: "s5",
    propiedadId: "p5",
  },

  // ── Calificados ──
  {
    id: "l6",
    nombre: "Familia Zaldaña Rivera",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "calificado",
    formaPago: "banco",
    presupuesto: 210000,
    zona: "Santa Tecla",
    busca: "Casa de 3 habitaciones con patio",
    hace: 2,
    asesorId: "s2",
    nota: "Carta de aprobación del banco por 195 mil.",
    propiedadId: "p3",
  },
  {
    id: "l7",
    nombre: "Ernesto Sibrián",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "calificado",
    formaPago: "contado",
    presupuesto: 450000,
    zona: "Colonia Escalón",
    busca: "Casa grande con estudio",
    hace: 1,
    asesorId: "me",
    nota: "Vende otra propiedad, paga de contado.",
    propiedadId: "p1",
  },
  {
    id: "l8",
    nombre: "Sandra Melgar de Ayala",
    canal: "messenger",
    operacion: "venta",
    etapa: "calificado",
    formaPago: "fsv",
    presupuesto: 78000,
    zona: "La Libertad",
    busca: "Casa que califique para FSV",
    hace: 3,
    asesorId: "s4",
    nota: "Cotización del FSV lista, cuota aprobada.",
    propiedadId: "p8",
  },
  {
    id: "l9",
    nombre: "Iván Portillo Cardoza",
    canal: "instagram",
    operacion: "venta",
    etapa: "calificado",
    formaPago: "banco",
    presupuesto: 270000,
    zona: "Zona Rosa",
    busca: "Apartamento de 2 habitaciones",
    hace: 6,
    asesorId: "s3",
    propiedadId: "p2",
  },
  {
    id: "l10",
    nombre: "Claudia Beatriz Lemus",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "calificado",
    formaPago: "fsv",
    presupuesto: 82000,
    zona: "Santa Tecla",
    busca: "Casa pequeña con dos parqueos",
    hace: 12,
    asesorId: "s4",
    nota: "Quedó de mandar constancia de salario y no la mandó.",
  },

  // ── No calificados (todavía no pueden, no son basura) ──
  {
    id: "l11",
    nombre: "Douglas Alfaro",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "no_calificado",
    formaPago: "fsv",
    presupuesto: 70000,
    zona: "San Salvador",
    busca: "Casa de 2 habitaciones",
    hace: 38,
    asesorId: "s4",
    nota: "Le falta un año de cotizaciones. Volver a buscarlo en marzo.",
  },
  {
    id: "l12",
    nombre: "Rosa Elena Chávez",
    canal: "messenger",
    operacion: "venta",
    etapa: "no_calificado",
    formaPago: "banco",
    presupuesto: 150000,
    zona: "Antiguo Cuscatlán",
    busca: "Casa en Merliot",
    hace: 54,
    asesorId: "s3",
    nota: "El banco le pidió limpiar dos deudas antes de volver a aplicar.",
  },
  {
    id: "l13",
    nombre: "Kevin Josué Mendoza",
    canal: "instagram",
    operacion: "venta",
    etapa: "no_calificado",
    formaPago: "sin_definir",
    presupuesto: 65000,
    zona: "San Salvador",
    busca: "Lo que alcance con poca prima",
    hace: 97,
    asesorId: "s2",
    nota: "Sin prima. Dijo que juntaba durante el año.",
  },

  // ── Visitas agendadas ──
  {
    id: "l14",
    nombre: "Mario y Xiomara Escobar",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "visita",
    formaPago: "banco",
    presupuesto: 200000,
    zona: "Santa Tecla",
    busca: "Casa en residencial con garita",
    hace: 1,
    asesorId: "s2",
    nota: "Vienen los dos. Él es el que decide.",
    propiedadId: "p3",
    visita: { propiedadId: "p3", enDias: 0, hora: "09:00", confirmada: true },
  },
  {
    id: "l15",
    nombre: "Luis Fernando Quintanilla",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "visita",
    formaPago: "contado",
    presupuesto: 260000,
    zona: "Paseo El Carmen",
    busca: "Local para cafetería",
    hace: 3,
    asesorId: "s5",
    propiedadId: "p6",
    visita: { propiedadId: "p6", enDias: 1, hora: "11:00", confirmada: true },
  },
  {
    id: "l16",
    nombre: "Ana Lucía Deras",
    canal: "messenger",
    operacion: "venta",
    etapa: "visita",
    formaPago: "fsv",
    presupuesto: 79000,
    zona: "La Libertad",
    busca: "Casa apta para FSV",
    hace: 8,
    asesorId: "s4",
    nota: "Reagendó dos veces. Confirmar el día antes.",
    propiedadId: "p8",
    visita: {
      propiedadId: "p8",
      enDias: 4,
      hora: "09:30",
      confirmada: false,
      nota: "Llamarla la noche antes o no llega.",
    },
  },
  {
    id: "l17",
    nombre: "Carlos Alberto Interiano",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "visita",
    formaPago: "sin_definir",
    presupuesto: 350000,
    zona: "Nuevo Cuscatlán",
    busca: "Casa con jardín",
    hace: 5,
    asesorId: "me",
    propiedadId: "p9",
    visita: { propiedadId: "p9", enDias: 0, hora: "15:00", confirmada: false },
  },

  // ── Ofertas ──
  {
    id: "l18",
    nombre: "Roberto Cañas Villeda",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "oferta",
    formaPago: "contado",
    presupuesto: 400000,
    zona: "Colonia Escalón",
    busca: "Casa de 4 habitaciones",
    hace: 2,
    asesorId: "me",
    nota: "Ofreció 398 mil. El propietario contraofertó.",
    propiedadId: "p1",
  },
  {
    id: "l19",
    nombre: "Verónica Aguilar",
    canal: "instagram",
    operacion: "venta",
    etapa: "oferta",
    formaPago: "banco",
    presupuesto: 255000,
    zona: "Zona Rosa",
    busca: "Apartamento con balcón",
    hace: 4,
    asesorId: "s3",
    nota: "Espera el avalúo del banco.",
    propiedadId: "p2",
  },
  {
    id: "l20",
    nombre: "Inversiones Palo Verde",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "oferta",
    formaPago: "contado",
    presupuesto: 115000,
    zona: "La Libertad",
    busca: "Terreno para proyecto de cabañas",
    hace: 11,
    asesorId: "s5",
    nota: "Ofrecieron 110 mil y no han vuelto a escribir.",
    propiedadId: "p5",
  },

  // ── Cerrados ──
  {
    id: "l21",
    nombre: "Jorge Bolaños Peña",
    canal: "whatsapp",
    operacion: "venta",
    etapa: "cerrado",
    formaPago: "banco",
    presupuesto: 158000,
    zona: "Santa Elena",
    busca: "Apartamento de 2 habitaciones",
    hace: 6,
    asesorId: "s3",
    nota: "Escrituró la semana pasada.",
    propiedadId: "p7",
  },
  {
    id: "l22",
    nombre: "Patricia Elizabeth Molina",
    canal: "messenger",
    operacion: "venta",
    etapa: "cerrado",
    formaPago: "fsv",
    presupuesto: 74000,
    zona: "La Libertad",
    busca: "Casa apta para FSV",
    hace: 21,
    asesorId: "s4",
    nota: "Crédito del FSV desembolsado.",
  },

  // ── Alquiler ──
  // Aquí el presupuesto es lo que puede pagar AL MES, y lo que califica no es el
  // FSV ni el banco: es con qué respalda la renta y desde cuándo la necesita.
  {
    id: "l23",
    nombre: "Kimberly Ayala",
    canal: "whatsapp",
    operacion: "alquiler",
    etapa: "nuevo",
    respaldo: "ingreso",
    mudanzaEnDias: 20,
    presupuesto: 600,
    zona: "Colonia Escalón",
    busca: "Apartamento de una habitación",
    hace: 0,
    asesorId: "s2",
    nota: "Escribió por el anuncio de TZ-116.",
    propiedadId: "p16",
  },
  {
    id: "l24",
    nombre: "Jonathan Rivera Melgar",
    canal: "instagram",
    operacion: "alquiler",
    etapa: "nuevo",
    respaldo: "sin_definir",
    mudanzaEnDias: 45,
    presupuesto: 800,
    zona: "Antiguo Cuscatlán",
    busca: "Apartamento amueblado",
    hace: 3,
    asesorId: "s3",
  },
  {
    id: "l25",
    nombre: "Doris Elena Campos",
    canal: "whatsapp",
    operacion: "alquiler",
    etapa: "calificado",
    respaldo: "fiador",
    mudanzaEnDias: 5,
    presupuesto: 1000,
    zona: "Santa Tecla",
    busca: "Casa de 3 habitaciones para la familia",
    hace: 1,
    asesorId: "s4",
    nota: "El fiador es su hermano y ya firmó con nosotros antes.",
    propiedadId: "p14",
  },
  {
    id: "l26",
    nombre: "Café Las Nubes",
    canal: "messenger",
    operacion: "alquiler",
    etapa: "visita",
    respaldo: "deposito",
    mudanzaEnDias: 30,
    presupuesto: 1300,
    zona: "Colonia Escalón",
    busca: "Local para cafetería",
    hace: 2,
    asesorId: "s5",
    nota: "Pagan tres meses adelantados en vez de poner fiador.",
    propiedadId: "p15",
    // Queda pegada a la de las 9 en Santa Tecla y en otro municipio: es el
    // choque que el tablero tiene que cantar.
    visita: { propiedadId: "p15", enDias: 0, hora: "10:15", confirmada: true },
  },
  {
    id: "l27",
    nombre: "Marvin Alexander Cañas",
    canal: "whatsapp",
    operacion: "alquiler",
    etapa: "no_calificado",
    respaldo: "sin_definir",
    mudanzaEnDias: 3,
    presupuesto: 450,
    zona: "San Salvador",
    busca: "Apartamento de una habitación",
    hace: 30,
    asesorId: "s2",
    nota: "Sin fiador y sin constancia de salario. Trabaja por su cuenta.",
  },
  {
    id: "l28",
    nombre: "Estefany Rodríguez",
    canal: "whatsapp",
    operacion: "alquiler",
    etapa: "oferta",
    respaldo: "ingreso",
    mudanzaEnDias: 12,
    presupuesto: 750,
    zona: "Antiguo Cuscatlán",
    busca: "Apartamento amueblado",
    hace: 1,
    asesorId: "s3",
    nota: "Contrato redactado, falta la firma del propietario.",
    propiedadId: "p13",
  },
  {
    id: "l29",
    nombre: "Wilfredo Menjívar",
    canal: "comentario",
    operacion: "alquiler",
    etapa: "visita",
    respaldo: "ingreso",
    mudanzaEnDias: 25,
    presupuesto: 950,
    zona: "Santa Tecla",
    busca: "Casa con patio",
    hace: 6,
    asesorId: "s2",
    nota: "Comentó en la publicación de TZ-114 y quedó de confirmar el día.",
    propiedadId: "p14",
    visita: { propiedadId: "p14", enDias: 2, hora: "16:30", confirmada: false },
  },
  {
    id: "l30",
    nombre: "Familia Handal Rivas",
    canal: "messenger",
    operacion: "alquiler",
    etapa: "cerrado",
    respaldo: "deposito",
    mudanzaEnDias: 0,
    presupuesto: 525,
    zona: "San Salvador",
    busca: "Apartamento de una habitación",
    hace: 9,
    asesorId: "s4",
    nota: "Firmaron y recibieron llaves. TZ-116 ya no está libre.",
    propiedadId: "p16",
  },
];
